site_name: BitBully Databases Docs
theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate   # (optional) Enables annotation features for clarity
    - content.code.select
  code_copy:
    remove_prompts: true
nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - User Guide: user_guide.md
  - API Reference:
      - bitbully_databases: python.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
- search
- mkdocstrings

# Note that there were/are issues with click:
# https://github.com/mkdocs/mkdocs/issues/4032
# Be careful when updating click
watch:
- src/bitbully_databases/
- docs/
- mkdocs.yml
