name: Build

on:
  push:
    tags:
      - "v*"  # Runs only on new tags starting with 'v'
  workflow_dispatch:  # Allow manual triggering

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10 # Consider increasing timeout
    strategy:
      fail-fast: false
      matrix:
        # [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-13, macos-latest]
        os: [ ubuntu-latest ]
        python-version: [3.11] # could also add more versions here, to test builds in different python versions

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # Used to host
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install build
        run: |
          python -m pip install build

      # Release build (use pyproject.toml)
      - name: Build wheels (regular)
        run: python -m build --outdir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: sdist
          path: dist/*.tar.gz

  # Add this job next to build_wheels / build_sdist
  test_wheel:
    name: Test wheel on ${{ matrix.os }} / py${{ matrix.python-version }}
    needs: [ build_wheels ]          # wait for wheels to be built
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.10", "3.11" , "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Pull only the wheel artifacts (adjust pattern to your artifact name)
      - uses: actions/download-artifact@v4
        with:
          #pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Show downloaded artifacts
        run: ls -lah dist
        shell: bash

      - name: Install test deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
        shell: bash

      # Install the built wheel (universal py3-none-any works everywhere)
      - name: Install wheel
        run: |
          python -m pip install dist/*.whl
          python -c "import bitbully_databases as m; print('Installed:', m.__version__)"
        shell: bash

      # Run your tests from the repo against the installed package
      - name: Run tests
        run: pytest -vv
        shell: bash

  # https://cibuildwheel.pypa.io/en/stable/deliver-to-pypi/
  upload_pypi:
    needs: [ build_wheels, build_sdist, test_wheel ]
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write

    #if: github.event_name == 'release' && github.event.action == 'published'
    # or, alternatively, upload to PyPI on every tag starting with 'v' (remove on: release above to use this)
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all  artifacts into dist/
          pattern: "*"
          path: dist
          merge-multiple: true

      # Upload pre-releases to TestPyPI only
      - name: Publish to TestPyPI (pre-releases)
        if: "contains(github.ref, '-')"   # Only run for tags like v1.0.0-rc1, v1.0.0-a2, etc.
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          repository-url: https://test.pypi.org/legacy/

      # publish to main PyPI
      - name: Publish to PyPI (stable releases)
        if: "!contains(github.ref, '-')"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          # attestations: false # Turn attestations off in case of issues

  delete_artifacts:
    name: Delete unnecessary GitHub Artifacts
    runs-on: ubuntu-latest
    needs: [ build_wheels, build_sdist, upload_pypi ]
    if: always()  # Ensure this job always runs
    steps:
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: |
            cibw-wheels-*
            cibw-sdist
